In [1]:
import numpy as np
from funcs import *

In [2]:
A=np.array([[1,2,0,1],[3,4,1,0],[0,1,0,0],[1,0,0,0]])
A

array([[1, 2, 0, 1],
       [3, 4, 1, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0]])

In [3]:
B=np.array([[0,0,0,1],[0,1,0,0],[0,0,1,0],[1,0,0,0]])
B

array([[0, 0, 0, 1],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0]])

In [4]:
partition_A=np.array([np.array([2, 2]), np.array([2 , 2])],dtype=object)
partition_B=np.array([np.array([2,2]), np.array([2 , 2])],dtype=object)

In [5]:
tracy_sing(A,B,partition_A,partition_B)

array([[0., 0., 0., 0., 0., 1., 0., 2., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 2., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 3., 0., 4., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 3., 0., 4., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 2., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 2., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 3., 0., 4., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [3., 0., 4., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,